### ISSUE TITLE
Cannot compile/install [Gradle 6]

### ISSUE THREAD

**Issue by flodi** [c64lib/gradle-retro-assembler-plugin#6]
Using gradle 6.0
I get this
Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

**Comment by maciejmalecki** [comment]
@flodi Gradle 6 is quite fresh and I haven't even tried yet whether it works (apparently not). What exactly are you trying to do: compile this plugin or use this plugin with Asm project?

**Comment by maciejmalecki** [comment]
Version 1.0.1 is out, now it works with Gradle 6. Please retest.
